# Generated by Django 3.2.5 on 2023-01-31 06:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactoconsulta',
            name='fecha_consulta',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
