# Generated by Django 3.2.5 on 2023-01-31 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0002_alter_contactoconsulta_fecha_consulta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactorespuesta',
            old_name='fecha_consulta',
            new_name='fecha_respuesta',
        ),
    ]
