# Generated by Django 3.2.5 on 2023-01-31 07:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0003_rename_fecha_consulta_contactorespuesta_fecha_respuesta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactorespuesta',
            name='fecha_respuesta',
            field=models.DateField(blank=True, verbose_name=datetime.datetime.now),
        ),
    ]
