# Generated by Django 3.2.5 on 2023-01-31 07:18

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0004_alter_contactorespuesta_fecha_respuesta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactorespuesta',
            name='consulta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contacto.contactoconsulta'),
        ),
        migrations.AlterField(
            model_name='contactorespuesta',
            name='fecha_respuesta',
            field=models.DateField(blank=True, editable=False, verbose_name=datetime.datetime.now),
        ),
    ]
