# Generated by Django 3.2.5 on 2023-01-31 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0005_auto_20230131_0418'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactoconsulta',
            old_name='fecha_consulta',
            new_name='fecha',
        ),
        migrations.RenameField(
            model_name='contactorespuesta',
            old_name='fecha_respuesta',
            new_name='fecha',
        ),
    ]
