# Generated by Django 3.2.5 on 2023-01-31 07:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0006_auto_20230131_0424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactorespuesta',
            name='fecha',
            field=models.DateField(blank=True, verbose_name=datetime.datetime.now),
        ),
    ]
