# Generated by Django 3.2.5 on 2022-12-27 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='dispositivo',
        ),
        migrations.RemoveField(
            model_name='store',
            name='email',
        ),
    ]
