# Generated by Django 3.2.5 on 2022-12-27 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20221227_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='cantidad_disponible',
            field=models.IntegerField(verbose_name='Unidades Disponibles'),
        ),
    ]
