# Generated by Django 3.2.5 on 2023-01-10 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_store_stock_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='producto',
            field=models.CharField(choices=[('Filtro 80x80mm', 'Filtro 80x80mm'), ('Filtro 120x120mm', 'Filtro 120x120mm'), ('Filtro 140x140mm', 'Filtro 140x140mm'), ('Disco Rigido', 'Disco Rigido'), ('Software', 'Software'), ('Directories Lister', 'Directories Lister'), ('Meta Data Extractor', 'Meta Data Extractor')], max_length=60),
        ),
    ]
