# Generated by Django 3.2.5 on 2023-01-10 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_store_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='descripcion_corta',
            field=models.CharField(default='aaa', max_length=20),
        ),
    ]
