# Generated by Django 3.2.5 on 2023-01-10 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_store_descripcion_corta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='descripcion',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='store',
            name='descripcion_corta',
            field=models.CharField(max_length=40),
        ),
    ]
