# Generated by Django 3.2.5 on 2023-05-29 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicio', models.CharField(choices=[('Recupero De Datos', 'Recupero De Datos'), ('Borrado Seguro De Datos', 'Borrado Seguro De Datos'), ('Reparacion Pedal Guitarra/Bajo', 'Reparacion Pedal Guitarra/Bajo'), ('Reparacion Parlante', 'Reparacion Parlante'), ('Reparacion Joystick PS-4', 'Reparacion Joystick PS-4'), ('Reparacion Joystick PS-5', 'Reparacion Joystick PS-5'), ('Reparacion Joystick XBOX-ONE', 'Reparacion Joystick XBOX-ONE'), ('Reparacion Joystick XBOX-360', 'Reparacion Joystick XBOX-360'), ('Reparacion PC/Notebook', 'Reparacion PC/Notebook'), ('Reparaciones Varias', 'Reparaciones Varias')], max_length=30)),
                ('cliente', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('dispositivo', models.CharField(max_length=200)),
                ('descripcion', models.CharField(max_length=200)),
                ('descripcion_servicio', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha_ingreso', models.DateField(verbose_name='Fecha de Ingreso')),
                ('estado_actual', models.CharField(choices=[('En Espera Diagnostico', 'En Espera Diagnostico'), ('En Diagnostico', 'En Diagnostico'), ('Esperando Aprobacion Cliente', 'Esperando Aprobacion Cliente'), ('Servicio Iniciado', 'Servicio Iniciado'), ('Servicio Finalizado', 'Servicio Finalizado'), ('Pago Pendiente', 'Pago Pendiente'), ('Esperando Retiro', 'Esperando Retiro'), ('Entregado', 'Entregado'), ('No Aprobado Esperando Retiro', 'No Aprobado Esperando Retiro')], default='En Espera Diagnostico', max_length=30)),
                ('entrega_estimada', models.DateField(blank=True, null=True, verbose_name='Fecha Entrega')),
                ('valor_presupuestado1', models.IntegerField(blank=True, null=True, verbose_name='Valor Presupuestado AR$')),
                ('fecha_presupuesto', models.DateField(blank=True, null=True, verbose_name='Fecha Presupuesto')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='producto/%Y/%m/%d')),
            ],
        ),
    ]
