# Generated by Django 3.2.5 on 2022-11-23 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios_board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicios',
            name='valor_presupuestado1',
            field=models.IntegerField(default=int, verbose_name='Valor Presupuestado'),
            preserve_default=False,
        ),
    ]
