# Generated by Django 3.2.5 on 2022-11-24 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios_board', '0003_auto_20221123_0524'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='producto/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='valor_presupuestado1',
            field=models.IntegerField(verbose_name='Valor Presupuestado AR$'),
        ),
    ]
