# Generated by Django 3.2.5 on 2022-11-24 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios_board', '0004_auto_20221124_0131'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_actual', models.CharField(db_index=True, max_length=100)),
                ('slug', models.SlugField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='estado_actual',
        ),
        migrations.AddField(
            model_name='servicio',
            name='categoria',
            field=models.ManyToManyField(to='servicios_board.Categoria'),
        ),
    ]
