# Generated by Django 3.2.5 on 2022-11-24 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios_board', '0005_auto_20221124_0202'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='descripcion_servicio',
            field=models.CharField(default=str, max_length=200),
            preserve_default=False,
        ),
    ]
