# Generated by Django 3.2.5 on 2022-11-24 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios_board', '0006_servicio_descripcion_servicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='descripcion_servicio',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
