# Generated by Django 3.2.5 on 2022-11-24 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios_board', '0008_auto_20221124_0506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='entrega_estimada',
            field=models.DateField(verbose_name='Fecha Entrega'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='fecha_ingreso',
            field=models.DateField(verbose_name='Fecha de Ingreso'),
        ),
    ]
