# Generated by Django 3.2.5 on 2022-11-24 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios_board', '0009_auto_20221124_0509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='entrega_estimada',
        ),
        migrations.AddField(
            model_name='servicio',
            name='Fecha Entrega',
            field=models.DateField(null=True),
        ),
    ]
