# Generated by Django 3.2.5 on 2022-11-24 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios_board', '0010_auto_20221124_0523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='Fecha Entrega',
        ),
        migrations.AddField(
            model_name='servicio',
            name='entrega_estimada',
            field=models.DateField(null=True, verbose_name='Fecha Entrega'),
        ),
    ]
