# Generated by Django 3.2.5 on 2022-11-24 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios_board', '0011_auto_20221124_0524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='descripcion_servicio',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='entrega_estimada',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Entrega'),
        ),
    ]
