# Generated by Django 3.2.5 on 2022-11-24 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios_board', '0012_auto_20221124_0546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='fecha_presupuesto',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Presupuesto'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='valor_presupuestado1',
            field=models.IntegerField(blank=True, null=True, verbose_name='Valor Presupuestado AR$'),
        ),
    ]
