# Generated by Django 3.2.5 on 2022-11-24 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios_board', '0013_auto_20221124_0548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='servicio',
            field=models.CharField(choices=[('En Espera Diagnostico', 'En Espera Diagnostico'), ('En Diagnostico', 'En Diagnostico'), ('Esperando Aprobacion Cliente', 'Esperando Aprobacion Cliente'), ('Servicio Iniciado', 'Servicio Iniciado'), ('Servicio Finalizado', 'Servicio Finalizado'), ('Pago Pendiente', 'Pago Pendiente'), ('Esperando Retiro', 'Esperando Retiro'), ('Entregado', 'Entregado')], default='Recupero De Datos', max_length=30),
        ),
    ]
