# Generated by Django 3.2.5 on 2023-05-29 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costoenvios', '0002_auto_20230529_0447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costosenvios',
            name='estado_actual',
            field=models.CharField(choices=[('Destino No Activo', 'Destino No Activo'), ('Destino Activo', 'Destino Activo'), ('Actualizar', 'Actualizar')], default='Destino Activo', max_length=30),
        ),
    ]
